version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=UTC
      - PORT=8081
      - HOST=0.0.0.0
      - LOG_LEVEL=debug
      - APP_KEY=QU3bPZtVbBgV3Hjl5YSazM_UCp505C_x
      - NODE_ENV=development
      - SESSION_DRIVER=cookie
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=blueskybluesky
      - DB_PASSWORD=blueskybluesky
      - DB_DATABASE=blueskybluesky
      - QUEUE_REDIS_HOST=redis
      - QUEUE_REDIS_PORT=6379
      - QUEUE_REDIS_PASSWORD=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: blueskybluesky
      POSTGRES_PASSWORD: blueskybluesky
      POSTGRES_DB: blueskybluesky
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.1-alpine
    ports:
      - 6379:6379

volumes:
  postgresql_data:
