version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=UTC
      - PORT=8081
      - HOST=0.0.0.0
      - LOG_LEVEL=debug
      - APP_KEY=QU3bPZtVbBgV3Hjl5YSazM_UCp505C_x
      - NODE_ENV=production
      - SESSION_DRIVER=cookie
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=blueskybluesky
      - DB_PASSWORD=blueskybluesky
      - DB_DATABASE=blueskybluesky
      - QUEUE_REDIS_HOST=redis
      - QUEUE_REDIS_PORT=6379
      - QUEUE_REDIS_PASSWORD=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    ports:
      - 8081:8081
    depends_on:
      - postgresql
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`bluesky-bot.com`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.docker.network=traefik_public
      - traefik.http.services.app.loadbalancer.server.port=8081
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=myresolver
    networks:
      - traefik_public
      - bluesky-copilot_default
  postgresql:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: blueskybluesky
      POSTGRES_PASSWORD: blueskybluesky
      POSTGRES_DB: blueskybluesky
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - bluesky-copilot_default
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U blueskybluesky']
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:7.4.1-alpine
    ports:
      - 6379:6379
    networks:
      - bluesky-copilot_default
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      retries: 5
      timeout: 5s

  reverse-proxy:
    image: traefik:v3.3
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=websecure
      - --certificatesresolvers.myresolver.acme.email=benameurallan06@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/acme.json
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    labels:
      - traefik.enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - - :/letsencrypt
    networks:
      - traefik_public

volumes:
  postgresql_data:

networks:
  traefik_public:
    driver: bridge
  bluesky-copilot_default:
    driver: bridge
